---
ansible_user: ec2-user
ansible_ssh_private_key_file: /home/bibawandaogo/devops_base/td2/scripts/ansible/sample-ap.pem
ansible_host_key_checking: false
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o IdentitiesOnly=yes'
