---
- name: Deploy an EC2 instance in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_region: us-east-2
    ami_id: ami-0900fe555666598a2
    instance_type: t3.micro
    key_name: ansible-ch2
    sg_name: sample-app-ansible
  tasks:
    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "{{ sg_name }}"
        description: "Allow HTTP(8080) and SSH"
        rules:
          - proto: tcp
            ports: [8080]
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports: [22]
            cidr_ip: 0.0.0.0/0
        region: "{{ aws_region }}"
      register: aws_security_group

    - name: Create EC2 key pair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        state: present
      register: aws_ec2_key_pair
      no_log: true

    - name: Save private key file (if created)
      copy:
        content: "{{ aws_ec2_key_pair.key.private_key }}"
        dest: "./{{ key_name }}.key"
        mode: '0600'
      when: aws_ec2_key_pair.changed

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: sample-app-ansible
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        security_groups:
          - "{{ aws_security_group.group_name }}"
        wait: true
        wait_timeout: 500
        region: "{{ aws_region }}"
        tags:
          Name: sample-app-ansible
          Ansible: ch2_instances
      register: ec2_instance

    - name: Display EC2 instance info
      debug:
        msg: >
          EC2 Instance {{ ec2_instance.instances[0].instance_id }}
          launched at {{ ec2_instance.instances[0].public_ip_address }}
