name: Infrastructure Tests

on: push

jobs:
  opentofu_test:
    name: "Run OpenTofu Tests"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN_TEST }}
          role-session-name: tests-${{ github.run_number }}-${{ github.actor }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
      
      - name: OpenTofu Test
        working-directory: TD5/scripts/tofu/live/lambda-sample
        env:
          TF_VAR_name: lambda-sample-${{ github.run_id }}
        run: |
          tofu init -backend=false -input=false
          tofu validate
          tofu test -verbose

